```mermaid
sequenceDiagram
    note over SDK, App: iBoxen = new SDK(ENV)

    App->>Backend: Select a parcel
    Backend->>iBoxen: GET /parcel/{parcelId}
    iBoxen->>Backend: Return parcel data: ParcelData

    Backend->>App: Return parcel data: ParcelData 
    note over App: parcel = iBoxen.loadParcelPayload(ParcelData)
    note over App: *Customer wants to open locker*
    App->>+SDK: parcel.openLocker()
    SDK->>-App: Result of openLocker

    note over App: Detect door closed

    App->>+SDK: parcel.isDoorClosed()
    SDK->>-App: Result of isDoorClosed

    note over App: *Customer finished with parcel*
    SDK->>iBoxen: parcel.setCollected()
```
